module Amazonite::LambdaV1
  # Contains details about a callback operation in a durable execution, including the callback token
  # and timeout configuration.
  class CallbackDetails
    include JSON::Serializable

    # The callback ID. Callback IDs are generated by the `DurableContext` when a durable function
    # calls `ctx.waitForCallback`.
    @[JSON::Field(key: "CallbackId")]
    property callback_id : String | Nil

    # The response payload from the callback operation as a string.
    @[JSON::Field(key: "Result")]
    property result : String | Nil

    # An error object that contains details about the failure.
    @[JSON::Field(key: "Error")]
    property error : ErrorObject | Nil

    def initialize(
      @callback_id : String | Nil = nil,
      @result : String | Nil = nil,
      @error : ErrorObject | Nil = nil,
    )
    end
  end
end
