private alias Core = Amazonite::Core

module Amazonite::LambdaV1
  # Contains details about a callback operation in a durable execution, including the callback token
  # and timeout configuration.
  class CallbackDetails
    include JSON::Serializable

    # The callback ID. Callback IDs are generated by the `DurableContext` when a durable function
    # calls `ctx.waitForCallback`.
    @[JSON::Field(key: "CallbackId")]
    property callback_id : String | Nil

    # The response payload from the callback operation as a string.
    @[JSON::Field(key: "Result")]
    property result : String | Nil

    # An error object that contains details about the failure.
    @[JSON::Field(key: "Error")]
    property error : ErrorObject | Nil

    def initialize(
      @callback_id : String | Nil = nil,
      @result : String | Nil = nil,
      @error : ErrorObject | Nil = nil,
    )
    end

    def validate! : Nil
      if value = @callback_id
        raise Core::ValidationError.new("CallbackId length must be >= 1") if value.size < 1
        raise Core::ValidationError.new("CallbackId length must be <= 1024") if value.size > 1024
        raise Core::ValidationError.new("CallbackId does not match the required pattern") unless value.matches?(Regex.new("^[A-Za-z0-9+/]+={0,2}$"))
      end

      if value = @result
        raise Core::ValidationError.new("Result length must be >= 0") if value.size < 0
        raise Core::ValidationError.new("Result length must be <= 6291456") if value.size > 6291456
      end

      if value = @error
        value.validate!
      end
    end

    def_equals_and_hash(@callback_id, @result, @error)
  end
end
