module Amazonite::LambdaV1
  # Contains details about a callback operation that has started, including timing information and
  # callback metadata.
  class CallbackStartedDetails
    include JSON::Serializable

    # The callback ID. Callback IDs are generated by the `DurableContext` when a durable function
    # calls `ctx.waitForCallback`.
    @[JSON::Field(key: "CallbackId")]
    property callback_id : String

    # The heartbeat timeout value, in seconds.
    @[JSON::Field(key: "HeartbeatTimeout")]
    property heartbeat_timeout : Int32 | Nil

    # The timeout value, in seconds.
    @[JSON::Field(key: "Timeout")]
    property timeout : Int32 | Nil

    def initialize(
      @callback_id : String,
      @heartbeat_timeout : Int32 | Nil = nil,
      @timeout : Int32 | Nil = nil,
    )
    end
  end
end
