Excluded:
  - src/compiler
  - src/dynamodb_v2
  - src/dynamodb_v2.cr

# Problems found: 6
# Run `ameba --only Metrics/CyclomaticComplexity` for details
Metrics/CyclomaticComplexity:
  Description: Disallows methods with a cyclomatic complexity higher than `MaxComplexity`
  MaxComplexity: 10
  Excluded:
  - spec/fixtures/templates/enum/batch_statement_error_code_enum.expected.cr
  - src/dynamo_v2/*.cr
  Enabled: true
  Severity: Convention

