private alias ACF = Amazonite::CloudFormation
private alias Core = Amazonite::Core

module Amazonite::CloudFormation
  # The input for DeleteStack action.
  class DeleteStackInput
    # The name or the unique stack ID that's associated with the stack.
    property stack_name : String

    # For stacks in the `DELETE_FAILED` state, a list of resource logical IDs that are associated with
    # the resources you want to retain. During deletion, CloudFormation deletes the stack but doesn't
    # delete the retained resources.
    #
    # Retaining resources is useful when you can't delete a resource, such as a non-empty S3 bucket,
    # but you want to delete the stack.
    property retain_resources : Array(String) | Nil

    # The Amazon Resource Name (ARN) of an IAM role that CloudFormation assumes to delete the stack.
    # CloudFormation uses the role's credentials to make calls on your behalf.
    #
    # If you don't specify a value, CloudFormation uses the role that was previously associated with
    # the stack. If no role is available, CloudFormation uses a temporary session that's generated
    # from your user credentials.
    property role_arn : String | Nil

    # A unique identifier for this `DeleteStack` request. Specify this token if you plan to retry
    # requests so that CloudFormation knows that you're not attempting to delete a stack with the same
    # name. You might retry `DeleteStack` requests to ensure that CloudFormation successfully received
    # them.
    #
    # All events initiated by a given stack operation are assigned the same client request token,
    # which you can use to track operations. For example, if you execute a `CreateStack` operation
    # with the token `token1`, then all the `StackEvents` generated by that operation will have
    # `ClientRequestToken` set as `token1`.
    #
    # In the console, stack operations display the client request token on the Events tab. Stack
    # operations that are initiated from the console use the token format *Console-StackOperation-ID*,
    # which helps you easily identify the stack operation . For example, if you create a stack using
    # the console, each stack event would be assigned the same token in the following format:
    # `Console-CreateStack-7f59c3cf-00d2-40c7-b2ff-e75db0987002`.
    property client_request_token : String | Nil

    # Specifies the deletion mode for the stack. Possible values are:
    #
    # - `STANDARD` - Use the standard behavior. Specifying this value is the same as not specifying
    # this parameter.
    #
    # - `FORCE_DELETE_STACK` - Delete the stack if it's stuck in a `DELETE_FAILED` state due to
    # resource deletion failure.
    property deletion_mode : DeletionMode | Nil

    # The deployment configuration for this stack operation, including the deployment mode.
    property deployment_config : DeploymentConfig | Nil

    def initialize(
      @stack_name : String,
      @retain_resources : Array(String) | Nil = nil,
      @role_arn : String | Nil = nil,
      @client_request_token : String | Nil = nil,
      @deletion_mode : DeletionMode | Nil = nil,
      @deployment_config : DeploymentConfig | Nil = nil,
    )
    end

    def to_query_params(prefix : String) : Array({String, String})
      params = [] of {String, String}

      params << {"#{prefix}StackName", @stack_name}

      (@retain_resources || [] of String).each_with_index(1) do |item, i|
        params << {"#{prefix}RetainResources.member.#{i}", item}
      end

      if value = @role_arn
        params << {"#{prefix}RoleARN", value}
      end

      if value = @client_request_token
        params << {"#{prefix}ClientRequestToken", value}
      end

      if value = @deletion_mode
        params << {"#{prefix}DeletionMode", value.to_json_object_key}
      end

      if value = @deployment_config
        params.concat(value.to_query_params("#{prefix}DeploymentConfig."))
      end
      params
    end

    def self.from_xml(node : XML::Node) : self
      new(
        stack_name: Core::XMLValue.string(node.xpath_node("*[local-name()='StackName']")).not_nil!,
        retain_resources: node.xpath_nodes("*[local-name()='RetainResources']/*[local-name()='member']").map { |n| n.content },
        role_arn: Core::XMLValue.string(node.xpath_node("*[local-name()='RoleARN']")),
        client_request_token: Core::XMLValue.string(node.xpath_node("*[local-name()='ClientRequestToken']")),
        deletion_mode: (n = node.xpath_node("*[local-name()='DeletionMode']")) ? ACF::DeletionMode.from_json_object_key?(n.content) : nil,
        deployment_config: node.xpath_node("*[local-name()='DeploymentConfig']").try { |n| DeploymentConfig.from_xml(n) },
      )
    end

    def validate! : Nil
      if value = @role_arn
        raise Core::ValidationError.new("RoleARN length must be >= 20") if value.size < 20
        raise Core::ValidationError.new("RoleARN length must be <= 2048") if value.size > 2048
      end

      if value = @client_request_token
        raise Core::ValidationError.new("ClientRequestToken length must be >= 1") if value.size < 1
        raise Core::ValidationError.new("ClientRequestToken length must be <= 128") if value.size > 128
        raise Core::ValidationError.new("ClientRequestToken does not match the required pattern") unless value.matches?(Regex.new("^[a-zA-Z0-9][-a-zA-Z0-9]*$"))
      end

      if value = @deployment_config
        value.validate!
      end
    end

    def_equals_and_hash(@stack_name, @retain_resources, @role_arn, @client_request_token, @deletion_mode, @deployment_config)
  end
end
