private alias Core = Amazonite::Core

module Amazonite::CloudWatchLogs
  # This object contains information about this Live Tail session, including the log groups included
  # and the log stream filters, if any.
  class LiveTailSessionStart
    include JSON::Serializable

    # The unique ID generated by CloudWatch Logs to identify this Live Tail session request.
    @[JSON::Field(key: "requestId")]
    property request_id : String | Nil

    # The unique ID generated by CloudWatch Logs to identify this Live Tail session.
    @[JSON::Field(key: "sessionId")]
    property session_id : String | Nil

    # An array of the names and ARNs of the log groups included in this Live Tail session.
    @[JSON::Field(key: "logGroupIdentifiers")]
    property log_group_identifiers : Array(String) | Nil

    # If your StartLiveTail operation request included a `logStreamNames` parameter that filtered the
    # session to only include certain log streams, these streams are listed here.
    @[JSON::Field(key: "logStreamNames")]
    property log_stream_names : Array(String) | Nil

    # If your StartLiveTail operation request included a `logStreamNamePrefixes` parameter that
    # filtered the session to only include log streams that have names that start with certain
    # prefixes, these prefixes are listed here.
    @[JSON::Field(key: "logStreamNamePrefixes")]
    property log_stream_name_prefixes : Array(String) | Nil

    # An optional pattern to filter the results to include only log events that match the pattern. For
    # example, a filter pattern of `error 404` displays only log events that include both `error` and
    # `404`.
    #
    # For more information about filter pattern syntax, see [Filter and Pattern
    # Syntax](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html).
    @[JSON::Field(key: "logEventFilterPattern")]
    property log_event_filter_pattern : String | Nil

    def initialize(
      @request_id : String | Nil = nil,
      @session_id : String | Nil = nil,
      @log_group_identifiers : Array(String) | Nil = nil,
      @log_stream_names : Array(String) | Nil = nil,
      @log_stream_name_prefixes : Array(String) | Nil = nil,
      @log_event_filter_pattern : String | Nil = nil,
    )
    end

    def validate! : Nil
      if value = @request_id
        raise Core::ValidationError.new("requestId length must be >= 0") if value.size < 0
        raise Core::ValidationError.new("requestId length must be <= 256") if value.size > 256
      end

      if value = @session_id
        raise Core::ValidationError.new("sessionId length must be >= 0") if value.size < 0
        raise Core::ValidationError.new("sessionId length must be <= 256") if value.size > 256
      end

      if value = @log_group_identifiers
        raise Core::ValidationError.new("logGroupIdentifiers must have at least 1 item(s)") if value.size < 1
        raise Core::ValidationError.new("logGroupIdentifiers must have at most 10 item(s)") if value.size > 10
      end

      if value = @log_stream_names
        raise Core::ValidationError.new("logStreamNames must have at least 1 item(s)") if value.size < 1
        raise Core::ValidationError.new("logStreamNames must have at most 100 item(s)") if value.size > 100
      end

      if value = @log_stream_name_prefixes
        raise Core::ValidationError.new("logStreamNamePrefixes must have at least 1 item(s)") if value.size < 1
        raise Core::ValidationError.new("logStreamNamePrefixes must have at most 100 item(s)") if value.size > 100
      end

      if value = @log_event_filter_pattern
        raise Core::ValidationError.new("logEventFilterPattern length must be >= 0") if value.size < 0
        raise Core::ValidationError.new("logEventFilterPattern length must be <= 1024") if value.size > 1024
      end
    end

    def_equals_and_hash(@request_id, @session_id, @log_group_identifiers, @log_stream_names, @log_stream_name_prefixes, @log_event_filter_pattern)
  end
end
