private alias AI = Amazonite::Iam
private alias Core = Amazonite::Core

module Amazonite::Iam
  class UpdateSAMLProviderRequest
    # An XML document generated by an identity provider (IdP) that supports SAML 2.0. The document
    # includes the issuer's name, expiration information, and keys that can be used to validate the
    # SAML authentication response (assertions) that are received from the IdP. You must generate the
    # metadata document using the identity management software that is used as your IdP.
    property saml_metadata_document : String | Nil

    # The Amazon Resource Name (ARN) of the SAML provider to update.
    #
    # For more information about ARNs, see [Amazon Resource Names
    # (ARNs)](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) in the
    # *Amazon Web Services General Reference*.
    property saml_provider_arn : String

    # Specifies the encryption setting for the SAML provider.
    property assertion_encryption_mode : AssertionEncryptionModeType | Nil

    # Specifies the new private key from your external identity provider. The private key must be a
    # .pem file that uses AES-GCM or AES-CBC encryption algorithm to decrypt SAML assertions.
    property add_private_key : String | Nil

    # The Key ID of the private key to remove.
    property remove_private_key : String | Nil

    def initialize(
      @saml_provider_arn : String,
      @saml_metadata_document : String | Nil = nil,
      @assertion_encryption_mode : AssertionEncryptionModeType | Nil = nil,
      @add_private_key : String | Nil = nil,
      @remove_private_key : String | Nil = nil,
    )
    end

    def to_query_params(prefix : String) : Array({String, String})
      params = [] of {String, String}

      if value = @saml_metadata_document
        params << {"#{prefix}SAMLMetadataDocument", value}
      end

      params << {"#{prefix}SAMLProviderArn", @saml_provider_arn}

      if value = @assertion_encryption_mode
        params << {"#{prefix}AssertionEncryptionMode", value.to_json_object_key}
      end

      if value = @add_private_key
        params << {"#{prefix}AddPrivateKey", value}
      end

      if value = @remove_private_key
        params << {"#{prefix}RemovePrivateKey", value}
      end
      params
    end

    def self.from_xml(node : XML::Node) : self
      new(
        saml_metadata_document: Core::XMLValue.string(node.xpath_node("*[local-name()='SAMLMetadataDocument']")),
        saml_provider_arn: Core::XMLValue.string(node.xpath_node("*[local-name()='SAMLProviderArn']")).not_nil!,
        assertion_encryption_mode: (n = node.xpath_node("*[local-name()='AssertionEncryptionMode']")) ? AI::AssertionEncryptionModeType.from_json_object_key?(n.content) : nil,
        add_private_key: Core::XMLValue.string(node.xpath_node("*[local-name()='AddPrivateKey']")),
        remove_private_key: Core::XMLValue.string(node.xpath_node("*[local-name()='RemovePrivateKey']")),
      )
    end

    def validate! : Nil
      if value = @saml_metadata_document
        raise Core::ValidationError.new("SAMLMetadataDocument length must be >= 1000") if value.size < 1000
        raise Core::ValidationError.new("SAMLMetadataDocument length must be <= 10000000") if value.size > 10000000
      end

      if value = @saml_provider_arn
        raise Core::ValidationError.new("SAMLProviderArn length must be >= 20") if value.size < 20
        raise Core::ValidationError.new("SAMLProviderArn length must be <= 2048") if value.size > 2048
      end

      if value = @add_private_key
        raise Core::ValidationError.new("AddPrivateKey length must be >= 1") if value.size < 1
        raise Core::ValidationError.new("AddPrivateKey length must be <= 16384") if value.size > 16384
        raise Core::ValidationError.new("AddPrivateKey does not match the required pattern") unless value.matches?(Regex.new("^[\t\n\r -ÿ]+$"))
      end

      if value = @remove_private_key
        raise Core::ValidationError.new("RemovePrivateKey length must be >= 22") if value.size < 22
        raise Core::ValidationError.new("RemovePrivateKey length must be <= 64") if value.size > 64
        raise Core::ValidationError.new("RemovePrivateKey does not match the required pattern") unless value.matches?(Regex.new("^[A-Z0-9]+$"))
      end
    end

    def_equals_and_hash(@saml_metadata_document, @saml_provider_arn, @assertion_encryption_mode, @add_private_key, @remove_private_key)
  end
end
