module Amazonite::KinesisV1
  class RegisterStreamConsumerOutput
    include JSON::Serializable

    # An object that represents the details of the consumer you registered. When you register a
    # consumer, it gets an ARN that is generated by Kinesis Data Streams.
    @[JSON::Field(key: "Consumer")]
    property consumer : Consumer

    def initialize(
      @consumer : Consumer,
    )
    end
  end
end
