private alias ACWL = Amazonite::CloudWatchLogsV1

module Amazonite::CloudWatchLogsV1
  # This structure represents one anomaly that has been found by a logs anomaly detector.
  #
  # For more information about patterns and anomalies, see
  # [CreateLogAnomalyDetector](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogAnomalyDetector.html).
  class Anomaly
    include JSON::Serializable

    # The unique ID that CloudWatch Logs assigned to this anomaly.
    @[JSON::Field(key: "anomalyId")]
    property anomaly_id : String

    # The ID of the pattern used to help identify this anomaly.
    @[JSON::Field(key: "patternId")]
    property pattern_id : String

    # The ARN of the anomaly detector that identified this anomaly.
    @[JSON::Field(key: "anomalyDetectorArn")]
    property anomaly_detector_arn : String

    # The pattern used to help identify this anomaly, in string format.
    @[JSON::Field(key: "patternString")]
    property pattern_string : String

    # The pattern used to help identify this anomaly, in regular expression format.
    @[JSON::Field(key: "patternRegex")]
    property pattern_regex : String | Nil

    # The priority level of this anomaly, as determined by CloudWatch Logs. Priority is computed based
    # on log severity labels such as `FATAL` and `ERROR` and the amount of deviation from the
    # baseline. Possible values are `HIGH`, `MEDIUM`, and `LOW`.
    @[JSON::Field(key: "priority")]
    property priority : String | Nil

    # The date and time when the anomaly detector first saw this anomaly. It is specified as epoch
    # time, which is the number of seconds since `January 1, 1970, 00:00:00 UTC`.
    @[JSON::Field(key: "firstSeen")]
    property first_seen : Int64

    # The date and time when the anomaly detector most recently saw this anomaly. It is specified as
    # epoch time, which is the number of seconds since `January 1, 1970, 00:00:00 UTC`.
    @[JSON::Field(key: "lastSeen")]
    property last_seen : Int64

    # A human-readable description of the anomaly. This description is generated by CloudWatch Logs.
    @[JSON::Field(key: "description")]
    property description : String

    # Specifies whether this anomaly is still ongoing.
    @[JSON::Field(key: "active")]
    property active : Bool

    # Indicates the current state of this anomaly. If it is still being treated as an anomaly, the
    # value is `Active`. If you have suppressed this anomaly by using the
    # [UpdateAnomaly](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_UpdateAnomaly.html)
    # operation, the value is `Suppressed`. If this behavior is now considered to be normal, the value
    # is `Baseline`.
    @[JSON::Field(key: "state", converter: ACWL::State)]
    property state : State

    # A map showing times when the anomaly detector ran, and the number of occurrences of this anomaly
    # that were detected at each of those runs. The times are specified in epoch time, which is the
    # number of seconds since `January 1, 1970, 00:00:00 UTC`.
    @[JSON::Field(key: "histogram")]
    property histogram : Hash(String, Int64)

    # An array of sample log event messages that are considered to be part of this anomaly.
    @[JSON::Field(key: "logSamples")]
    property log_samples : Array(LogEvent) = [] of LogEvent

    # An array of structures where each structure contains information about one token that makes up
    # the pattern.
    @[JSON::Field(key: "patternTokens")]
    property pattern_tokens : Array(PatternToken) = [] of PatternToken

    # An array of ARNS of the log groups that contained log events considered to be part of this
    # anomaly.
    @[JSON::Field(key: "logGroupArnList")]
    property log_group_arn_list : Array(String) = [] of String

    # Indicates whether this anomaly is currently suppressed. To suppress an anomaly, use
    # [UpdateAnomaly](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_UpdateAnomaly.html).
    @[JSON::Field(key: "suppressed")]
    property suppressed : Bool | Nil

    # If the anomaly is suppressed, this indicates when it was suppressed.
    @[JSON::Field(key: "suppressedDate")]
    property suppressed_date : Int64 | Nil

    # If the anomaly is suppressed, this indicates when the suppression will end. If this value is
    # `0`, the anomaly was suppressed with no expiration, with the `INFINITE` value.
    @[JSON::Field(key: "suppressedUntil")]
    property suppressed_until : Int64 | Nil

    # If this anomaly is suppressed, this field is `true` if the suppression is because the pattern is
    # suppressed. If `false`, then only this particular anomaly is suppressed.
    @[JSON::Field(key: "isPatternLevelSuppression")]
    property is_pattern_level_suppression : Bool | Nil

    def initialize(
      @anomaly_id : String,
      @pattern_id : String,
      @anomaly_detector_arn : String,
      @pattern_string : String,
      @first_seen : Int64,
      @last_seen : Int64,
      @description : String,
      @active : Bool,
      @state : State,
      @histogram : Hash(String, Int64),
      @log_samples : Array(LogEvent),
      @pattern_tokens : Array(PatternToken),
      @log_group_arn_list : Array(String),
      @pattern_regex : String | Nil = nil,
      @priority : String | Nil = nil,
      @suppressed : Bool | Nil = nil,
      @suppressed_date : Int64 | Nil = nil,
      @suppressed_until : Int64 | Nil = nil,
      @is_pattern_level_suppression : Bool | Nil = nil,
    )
    end

    def_equals_and_hash(@anomaly_id, @pattern_id, @anomaly_detector_arn, @pattern_string, @pattern_regex, @priority, @first_seen, @last_seen, @description, @active, @state, @histogram, @log_samples, @pattern_tokens, @log_group_arn_list, @suppressed, @suppressed_date, @suppressed_until, @is_pattern_level_suppression)
  end
end
