module Amazonite::CloudWatchLogsV1
  # This object contains information about this Live Tail session, including the log groups included
  # and the log stream filters, if any.
  class LiveTailSessionStart
    include JSON::Serializable

    # The unique ID generated by CloudWatch Logs to identify this Live Tail session request.
    @[JSON::Field(key: "requestId")]
    property request_id : String | Nil

    # The unique ID generated by CloudWatch Logs to identify this Live Tail session.
    @[JSON::Field(key: "sessionId")]
    property session_id : String | Nil

    # An array of the names and ARNs of the log groups included in this Live Tail session.
    @[JSON::Field(key: "logGroupIdentifiers")]
    property log_group_identifiers : Array(String) | Nil

    # If your StartLiveTail operation request included a `logStreamNames` parameter that filtered the
    # session to only include certain log streams, these streams are listed here.
    @[JSON::Field(key: "logStreamNames")]
    property log_stream_names : Array(String) | Nil

    # If your StartLiveTail operation request included a `logStreamNamePrefixes` parameter that
    # filtered the session to only include log streams that have names that start with certain
    # prefixes, these prefixes are listed here.
    @[JSON::Field(key: "logStreamNamePrefixes")]
    property log_stream_name_prefixes : Array(String) | Nil

    # An optional pattern to filter the results to include only log events that match the pattern. For
    # example, a filter pattern of `error 404` displays only log events that include both `error` and
    # `404`.
    #
    # For more information about filter pattern syntax, see [Filter and Pattern
    # Syntax](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html).
    @[JSON::Field(key: "logEventFilterPattern")]
    property log_event_filter_pattern : String | Nil

    def initialize(
      @request_id : String | Nil = nil,
      @session_id : String | Nil = nil,
      @log_group_identifiers : Array(String) | Nil = nil,
      @log_stream_names : Array(String) | Nil = nil,
      @log_stream_name_prefixes : Array(String) | Nil = nil,
      @log_event_filter_pattern : String | Nil = nil,
    )
    end
  end
end
