private alias Core = Amazonite::Core

module Amazonite::StsV1
  # The identifiers for the temporary security credentials that the operation returns.
  class AssumedRoleUser
    # A unique identifier that contains the role ID and the role session name of the role that is
    # being assumed. The role ID is generated by Amazon Web Services when the role is created.
    property assumed_role_id : String

    # The ARN of the temporary security credentials that are returned from the AssumeRole action. For
    # more information about ARNs and how to use them in policies, see [IAM
    # Identifiers](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html) in the
    # *IAM User Guide*.
    property arn : String

    def initialize(
      @assumed_role_id : String,
      @arn : String,
    )
    end

    def to_query_params(prefix : String) : Array({String, String})
      params = [] of {String, String}

      params << {"#{prefix}AssumedRoleId", @assumed_role_id}

      params << {"#{prefix}Arn", @arn}
      params
    end

    def self.from_xml(node : XML::Node) : self
      new(
        assumed_role_id: Core::XMLValue.string(node.xpath_node("*[local-name()='AssumedRoleId']")).not_nil!,
        arn: Core::XMLValue.string(node.xpath_node("*[local-name()='Arn']")).not_nil!,
      )
    end

    def validate! : Nil
      if value = @assumed_role_id
        raise Core::ValidationError.new("AssumedRoleId length must be >= 2") if value.size < 2
        raise Core::ValidationError.new("AssumedRoleId length must be <= 193") if value.size > 193
        raise Core::ValidationError.new("AssumedRoleId does not match the required pattern") unless value.matches?(Regex.new("^[\\w+=,.@:-]*$"))
      end

      if value = @arn
        raise Core::ValidationError.new("Arn length must be >= 20") if value.size < 20
        raise Core::ValidationError.new("Arn length must be <= 2048") if value.size > 2048
        raise Core::ValidationError.new("Arn does not match the required pattern") unless value.matches?(Regex.new("^[\\u0009\\u000A\\u000D\\u0020-\\u007E\\u0085\\u00A0-\\uD7FF\\uE000-\\uFFFD\\u10000-\\u10FFFF]+$"))
      end
    end

    def_equals_and_hash(@assumed_role_id, @arn)
  end
end
