private alias Core = Amazonite::Core

module Amazonite::StsV1
  # Contains information about the provided context. This includes the signed and encrypted trusted
  # context assertion and the context provider ARN from which the trusted context assertion was
  # generated.
  class ProvidedContext
    # The context provider ARN from which the trusted context assertion was generated.
    property provider_arn : String | Nil

    # The signed and encrypted trusted context assertion generated by the context provider. The
    # trusted context assertion is signed and encrypted by Amazon Web Services STS.
    property context_assertion : String | Nil

    def initialize(
      @provider_arn : String | Nil = nil,
      @context_assertion : String | Nil = nil,
    )
    end

    def to_query_params(prefix : String) : Array({String, String})
      params = [] of {String, String}

      if value = @provider_arn
        params << {"#{prefix}ProviderArn", value}
      end

      if value = @context_assertion
        params << {"#{prefix}ContextAssertion", value}
      end
      params
    end

    def self.from_xml(node : XML::Node) : self
      new(
        provider_arn: Core::XMLValue.string(node.xpath_node("*[local-name()='ProviderArn']")),
        context_assertion: Core::XMLValue.string(node.xpath_node("*[local-name()='ContextAssertion']")),
      )
    end

    def validate! : Nil
      if value = @provider_arn
        raise Core::ValidationError.new("ProviderArn length must be >= 20") if value.size < 20
        raise Core::ValidationError.new("ProviderArn length must be <= 2048") if value.size > 2048
        raise Core::ValidationError.new("ProviderArn does not match the required pattern") unless value.matches?(Regex.new("^[\\u0009\\u000A\\u000D\\u0020-\\u007E\\u0085\\u00A0-\\uD7FF\\uE000-\\uFFFD\\u10000-\\u10FFFF]+$"))
      end

      if value = @context_assertion
        raise Core::ValidationError.new("ContextAssertion length must be >= 4") if value.size < 4
        raise Core::ValidationError.new("ContextAssertion length must be <= 2048") if value.size > 2048
      end
    end

    def_equals_and_hash(@provider_arn, @context_assertion)
  end
end
