private alias AAG = Amazonite::ApiGatewayV1

module Amazonite::ApiGatewayV1
  # A gateway response of a given response type and status code, with optional response parameters
  # and mapping templates.
  class GatewayResponse
    include JSON::Serializable

    # The response type of the associated GatewayResponse.
    @[JSON::Field(key: "responseType", converter: AAG::GatewayResponseType)]
    property response_type : GatewayResponseType | Nil

    # The HTTP status code for this GatewayResponse.
    @[JSON::Field(key: "statusCode")]
    property status_code : String | Nil

    # Response parameters (paths, query strings and headers) of the GatewayResponse as a
    # string-to-string map of key-value pairs.
    @[JSON::Field(key: "responseParameters")]
    property response_parameters : Hash(String, String) | Nil

    # Response templates of the GatewayResponse as a string-to-string map of key-value pairs.
    @[JSON::Field(key: "responseTemplates")]
    property response_templates : Hash(String, String) | Nil

    # A Boolean flag to indicate whether this GatewayResponse is the default gateway response (`true`)
    # or not (`false`). A default gateway response is one generated by API Gateway without any
    # customization by an API developer.
    @[JSON::Field(key: "defaultResponse")]
    property default_response : Bool | Nil

    def initialize(
      @response_type : GatewayResponseType | Nil = nil,
      @status_code : String | Nil = nil,
      @response_parameters : Hash(String, String) | Nil = nil,
      @response_templates : Hash(String, String) | Nil = nil,
      @default_response : Bool | Nil = nil,
    )
    end

    def_equals_and_hash(@response_type, @status_code, @response_parameters, @response_templates, @default_response)
  end
end
