private alias ACF = Amazonite::CloudFormationV1
private alias Core = Amazonite::Core

module Amazonite::CloudFormationV1
  # The `StackEvent` data type.
  class StackEvent
    # The unique ID name of the instance of the stack.
    property stack_id : String

    # The unique identifier of this event.
    property event_id : String

    # The name associated with a stack.
    property stack_name : String

    # The unique identifier of the operation that generated this stack event.
    property operation_id : String | Nil

    # The logical name of the resource specified in the template.
    property logical_resource_id : String | Nil

    # The name or unique identifier associated with the physical instance of the resource.
    property physical_resource_id : String | Nil

    # Type of resource. For more information, see [Amazon Web Services resource and property types
    # reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html)
    # in the *CloudFormation User Guide*.
    property resource_type : String | Nil

    # Time the status was updated.
    property timestamp : Time

    # Current status of the resource.
    property resource_status : ResourceStatus | Nil

    # Success/failure message associated with the resource.
    property resource_status_reason : String | Nil

    # BLOB of the properties used to create the resource.
    property resource_properties : String | Nil

    # The token passed to the operation that generated this event.
    #
    # All events triggered by a given stack operation are assigned the same client request token,
    # which you can use to track operations. For example, if you execute a `CreateStack` operation
    # with the token `token1`, then all the `StackEvents` generated by that operation will have
    # `ClientRequestToken` set as `token1`.
    #
    # In the console, stack operations display the client request token on the Events tab. Stack
    # operations that are initiated from the console use the token format *Console-StackOperation-ID*,
    # which helps you easily identify the stack operation . For example, if you create a stack using
    # the console, each stack event would be assigned the same token in the following format:
    # `Console-CreateStack-7f59c3cf-00d2-40c7-b2ff-e75db0987002`.
    property client_request_token : String | Nil

    # The name of the Hook.
    property hook_type : String | Nil

    # Provides the status of the change set Hook.
    property hook_status : HookStatus | Nil

    # Provides the reason for the Hook status.
    property hook_status_reason : String | Nil

    # The specific point in the provisioning process where the Hook is invoked.
    property hook_invocation_point : HookInvocationPoint | Nil

    # The unique identifier of the Hook invocation.
    property hook_invocation_id : String | Nil

    # Specify the Hook failure mode for non-compliant resources in the followings ways.
    #
    # - `FAIL` Stops provisioning resources.
    #
    # - `WARN` Allows provisioning to continue with a warning message.
    property hook_failure_mode : HookFailureMode | Nil

    # An optional field that contains information about the detailed status of the stack event.
    #
    # - `CONFIGURATION_COMPLETE` - all of the resources in the stack have reached that event. For more
    # information, see [Understand CloudFormation stack creation
    # events](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stack-resource-configuration-complete.html)
    # in the *CloudFormation User Guide*.
    #
    # - `VALIDATION_FAILED` - template validation failed because of invalid properties in the
    # template. The `ResourceStatusReason` field shows what properties are defined incorrectly.
    property detailed_status : DetailedStatus | Nil

    def initialize(
      @stack_id : String,
      @event_id : String,
      @stack_name : String,
      @timestamp : Time,
      @operation_id : String | Nil = nil,
      @logical_resource_id : String | Nil = nil,
      @physical_resource_id : String | Nil = nil,
      @resource_type : String | Nil = nil,
      @resource_status : ResourceStatus | Nil = nil,
      @resource_status_reason : String | Nil = nil,
      @resource_properties : String | Nil = nil,
      @client_request_token : String | Nil = nil,
      @hook_type : String | Nil = nil,
      @hook_status : HookStatus | Nil = nil,
      @hook_status_reason : String | Nil = nil,
      @hook_invocation_point : HookInvocationPoint | Nil = nil,
      @hook_invocation_id : String | Nil = nil,
      @hook_failure_mode : HookFailureMode | Nil = nil,
      @detailed_status : DetailedStatus | Nil = nil,
    )
    end

    def to_query_params(prefix : String) : Array({String, String})
      params = [] of {String, String}

      params << {"#{prefix}StackId", @stack_id}

      params << {"#{prefix}EventId", @event_id}

      params << {"#{prefix}StackName", @stack_name}

      if value = @operation_id
        params << {"#{prefix}OperationId", value}
      end

      if value = @logical_resource_id
        params << {"#{prefix}LogicalResourceId", value}
      end

      if value = @physical_resource_id
        params << {"#{prefix}PhysicalResourceId", value}
      end

      if value = @resource_type
        params << {"#{prefix}ResourceType", value}
      end

      params << {"#{prefix}Timestamp", Core::QueryValue.time(@timestamp)}

      if value = @resource_status
        params << {"#{prefix}ResourceStatus", value.to_json_object_key}
      end

      if value = @resource_status_reason
        params << {"#{prefix}ResourceStatusReason", value}
      end

      if value = @resource_properties
        params << {"#{prefix}ResourceProperties", value}
      end

      if value = @client_request_token
        params << {"#{prefix}ClientRequestToken", value}
      end

      if value = @hook_type
        params << {"#{prefix}HookType", value}
      end

      if value = @hook_status
        params << {"#{prefix}HookStatus", value.to_json_object_key}
      end

      if value = @hook_status_reason
        params << {"#{prefix}HookStatusReason", value}
      end

      if value = @hook_invocation_point
        params << {"#{prefix}HookInvocationPoint", value.to_json_object_key}
      end

      if value = @hook_invocation_id
        params << {"#{prefix}HookInvocationId", value}
      end

      if value = @hook_failure_mode
        params << {"#{prefix}HookFailureMode", value.to_json_object_key}
      end

      if value = @detailed_status
        params << {"#{prefix}DetailedStatus", value.to_json_object_key}
      end
      params
    end

    def self.from_xml(node : XML::Node) : self
      new(
        stack_id: Core::XMLValue.string(node.xpath_node("*[local-name()='StackId']")).not_nil!,
        event_id: Core::XMLValue.string(node.xpath_node("*[local-name()='EventId']")).not_nil!,
        stack_name: Core::XMLValue.string(node.xpath_node("*[local-name()='StackName']")).not_nil!,
        operation_id: Core::XMLValue.string(node.xpath_node("*[local-name()='OperationId']")),
        logical_resource_id: Core::XMLValue.string(node.xpath_node("*[local-name()='LogicalResourceId']")),
        physical_resource_id: Core::XMLValue.string(node.xpath_node("*[local-name()='PhysicalResourceId']")),
        resource_type: Core::XMLValue.string(node.xpath_node("*[local-name()='ResourceType']")),
        timestamp: Core::XMLValue.time(node.xpath_node("*[local-name()='Timestamp']")).not_nil!,
        resource_status: (n = node.xpath_node("*[local-name()='ResourceStatus']")) ? ACF::ResourceStatus.from_json_object_key?(n.content) : nil,
        resource_status_reason: Core::XMLValue.string(node.xpath_node("*[local-name()='ResourceStatusReason']")),
        resource_properties: Core::XMLValue.string(node.xpath_node("*[local-name()='ResourceProperties']")),
        client_request_token: Core::XMLValue.string(node.xpath_node("*[local-name()='ClientRequestToken']")),
        hook_type: Core::XMLValue.string(node.xpath_node("*[local-name()='HookType']")),
        hook_status: (n = node.xpath_node("*[local-name()='HookStatus']")) ? ACF::HookStatus.from_json_object_key?(n.content) : nil,
        hook_status_reason: Core::XMLValue.string(node.xpath_node("*[local-name()='HookStatusReason']")),
        hook_invocation_point: (n = node.xpath_node("*[local-name()='HookInvocationPoint']")) ? ACF::HookInvocationPoint.from_json_object_key?(n.content) : nil,
        hook_invocation_id: Core::XMLValue.string(node.xpath_node("*[local-name()='HookInvocationId']")),
        hook_failure_mode: (n = node.xpath_node("*[local-name()='HookFailureMode']")) ? ACF::HookFailureMode.from_json_object_key?(n.content) : nil,
        detailed_status: (n = node.xpath_node("*[local-name()='DetailedStatus']")) ? ACF::DetailedStatus.from_json_object_key?(n.content) : nil,
      )
    end

    def validate! : Nil
      if value = @resource_type
        raise Core::ValidationError.new("ResourceType length must be >= 1") if value.size < 1
        raise Core::ValidationError.new("ResourceType length must be <= 256") if value.size > 256
      end

      if value = @client_request_token
        raise Core::ValidationError.new("ClientRequestToken length must be >= 1") if value.size < 1
        raise Core::ValidationError.new("ClientRequestToken length must be <= 128") if value.size > 128
        raise Core::ValidationError.new("ClientRequestToken does not match the required pattern") unless value.matches?(Regex.new("^[a-zA-Z0-9][-a-zA-Z0-9]*$"))
      end

      if value = @hook_type
        raise Core::ValidationError.new("HookType length must be >= 1") if value.size < 1
        raise Core::ValidationError.new("HookType length must be <= 255") if value.size > 255
      end

      if value = @hook_status_reason
        raise Core::ValidationError.new("HookStatusReason length must be >= 1") if value.size < 1
        raise Core::ValidationError.new("HookStatusReason length must be <= 1024") if value.size > 1024
      end

      if value = @hook_invocation_id
        raise Core::ValidationError.new("HookInvocationId length must be >= 36") if value.size < 36
        raise Core::ValidationError.new("HookInvocationId length must be <= 36") if value.size > 36
        raise Core::ValidationError.new("HookInvocationId does not match the required pattern") unless value.matches?(Regex.new("^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$"))
      end
    end

    def_equals_and_hash(@stack_id, @event_id, @stack_name, @operation_id, @logical_resource_id, @physical_resource_id, @resource_type, @timestamp, @resource_status, @resource_status_reason, @resource_properties, @client_request_token, @hook_type, @hook_status, @hook_status_reason, @hook_invocation_point, @hook_invocation_id, @hook_failure_mode, @detailed_status)
  end
end
