private alias AEC = Amazonite::EC2
private alias Core = Amazonite::Core

module Amazonite::EC2
  class CreateVpcEndpointRequest
    # Checks whether you have the required permissions for the action, without actually making the
    # request, and provides an error response. If you have the required permissions, the error
    # response is `DryRunOperation`. Otherwise, it is `UnauthorizedOperation`.
    property dry_run : Bool | Nil

    # The type of endpoint.
    #
    # Default: Gateway
    property vpc_endpoint_type : VpcEndpointType | Nil

    # The ID of the VPC.
    property vpc_id : String

    # The name of the endpoint service.
    property service_name : String | Nil

    # (Interface and gateway endpoints) A policy to attach to the endpoint that controls access to the
    # service. The policy must be in valid JSON format. If this parameter is not specified, we attach
    # a default policy that allows full access to the service.
    property policy_document : String | Nil

    # (Gateway endpoint) The route table IDs.
    property route_table_ids : Array(String) | Nil

    # (Interface and Gateway Load Balancer endpoints) The IDs of the subnets in which to create
    # endpoint network interfaces. For a Gateway Load Balancer endpoint, you can specify only one
    # subnet.
    property subnet_ids : Array(String) | Nil

    # (Interface endpoint) The IDs of the security groups to associate with the endpoint network
    # interfaces. If this parameter is not specified, we use the default security group for the VPC.
    property security_group_ids : Array(String) | Nil

    # The IP address type for the endpoint.
    property ip_address_type : IpAddressType | Nil

    # The DNS options for the endpoint.
    property dns_options : DnsOptionsSpecification | Nil

    # Unique, case-sensitive identifier that you provide to ensure the idempotency of the request. For
    # more information, see [How to ensure
    # idempotency](https://docs.aws.amazon.com/ec2/latest/devguide/ec2-api-idempotency.html).
    property client_token : String | Nil

    # (Interface endpoint) Indicates whether to associate a private hosted zone with the specified
    # VPC. The private hosted zone contains a record set for the default public DNS name for the
    # service for the Region (for example, `kinesis.us-east-1.amazonaws.com`), which resolves to the
    # private IP addresses of the endpoint network interfaces in the VPC. This enables you to make
    # requests to the default public DNS name for the service instead of the public DNS names that are
    # automatically generated by the VPC endpoint service.
    #
    # To use a private hosted zone, you must set the following VPC attributes to `true`:
    # `enableDnsHostnames` and `enableDnsSupport`. Use ModifyVpcAttribute to set the VPC attributes.
    property private_dns_enabled : Bool | Nil

    # The tags to associate with the endpoint.
    property tag_specifications : Array(TagSpecification) | Nil

    # The subnet configurations for the endpoint.
    property subnet_configurations : Array(SubnetConfiguration) | Nil

    # The Amazon Resource Name (ARN) of a service network that will be associated with the VPC
    # endpoint of type service-network.
    property service_network_arn : String | Nil

    # The Amazon Resource Name (ARN) of a resource configuration that will be associated with the VPC
    # endpoint of type resource.
    property resource_configuration_arn : String | Nil

    # The Region where the service is hosted. The default is the current Region.
    property service_region : String | Nil

    def initialize(
      @vpc_id : String,
      @dry_run : Bool | Nil = nil,
      @vpc_endpoint_type : VpcEndpointType | Nil = nil,
      @service_name : String | Nil = nil,
      @policy_document : String | Nil = nil,
      @route_table_ids : Array(String) | Nil = nil,
      @subnet_ids : Array(String) | Nil = nil,
      @security_group_ids : Array(String) | Nil = nil,
      @ip_address_type : IpAddressType | Nil = nil,
      @dns_options : DnsOptionsSpecification | Nil = nil,
      @client_token : String | Nil = nil,
      @private_dns_enabled : Bool | Nil = nil,
      @tag_specifications : Array(TagSpecification) | Nil = nil,
      @subnet_configurations : Array(SubnetConfiguration) | Nil = nil,
      @service_network_arn : String | Nil = nil,
      @resource_configuration_arn : String | Nil = nil,
      @service_region : String | Nil = nil,
    )
    end

    def to_query_params(prefix : String) : Array({String, String})
      params = [] of {String, String}

      if value = @dry_run
        params << {"#{prefix}DryRun", Core::QueryValue.bool(value)}
      end

      if value = @vpc_endpoint_type
        params << {"#{prefix}VpcEndpointType", value.to_json_object_key}
      end

      params << {"#{prefix}VpcId", @vpc_id}

      if value = @service_name
        params << {"#{prefix}ServiceName", value}
      end

      if value = @policy_document
        params << {"#{prefix}PolicyDocument", value}
      end

      (@route_table_ids || [] of String).each_with_index(1) do |item, i|
        params << {"#{prefix}RouteTableId.#{i}", item}
      end

      (@subnet_ids || [] of String).each_with_index(1) do |item, i|
        params << {"#{prefix}SubnetId.#{i}", item}
      end

      (@security_group_ids || [] of String).each_with_index(1) do |item, i|
        params << {"#{prefix}SecurityGroupId.#{i}", item}
      end

      if value = @ip_address_type
        params << {"#{prefix}IpAddressType", value.to_json_object_key}
      end

      if value = @dns_options
        params.concat(value.to_query_params("#{prefix}DnsOptions."))
      end

      if value = @client_token
        params << {"#{prefix}ClientToken", value}
      end

      if value = @private_dns_enabled
        params << {"#{prefix}PrivateDnsEnabled", Core::QueryValue.bool(value)}
      end

      (@tag_specifications || [] of TagSpecification).each_with_index(1) do |item, i|
        params.concat(item.to_query_params("#{prefix}TagSpecification.#{i}."))
      end

      (@subnet_configurations || [] of SubnetConfiguration).each_with_index(1) do |item, i|
        params.concat(item.to_query_params("#{prefix}SubnetConfiguration.#{i}."))
      end

      if value = @service_network_arn
        params << {"#{prefix}ServiceNetworkArn", value}
      end

      if value = @resource_configuration_arn
        params << {"#{prefix}ResourceConfigurationArn", value}
      end

      if value = @service_region
        params << {"#{prefix}ServiceRegion", value}
      end
      params
    end

    def self.from_xml(node : XML::Node) : self
      new(
        dry_run: Core::XMLValue.bool(node.xpath_node("*[local-name()='DryRun']")),
        vpc_endpoint_type: (n = node.xpath_node("*[local-name()='VpcEndpointType']")) ? AEC::VpcEndpointType.from_json_object_key?(n.content) : nil,
        vpc_id: Core::XMLValue.string(node.xpath_node("*[local-name()='VpcId']")).not_nil!,
        service_name: Core::XMLValue.string(node.xpath_node("*[local-name()='ServiceName']")),
        policy_document: Core::XMLValue.string(node.xpath_node("*[local-name()='PolicyDocument']")),
        route_table_ids: node.xpath_nodes("*[local-name()='RouteTableId']/*[local-name()='item']").map { |n| n.content },
        subnet_ids: node.xpath_nodes("*[local-name()='SubnetId']/*[local-name()='item']").map { |n| n.content },
        security_group_ids: node.xpath_nodes("*[local-name()='SecurityGroupId']/*[local-name()='item']").map { |n| n.content },
        ip_address_type: (n = node.xpath_node("*[local-name()='IpAddressType']")) ? AEC::IpAddressType.from_json_object_key?(n.content) : nil,
        dns_options: node.xpath_node("*[local-name()='DnsOptions']").try { |n| DnsOptionsSpecification.from_xml(n) },
        client_token: Core::XMLValue.string(node.xpath_node("*[local-name()='ClientToken']")),
        private_dns_enabled: Core::XMLValue.bool(node.xpath_node("*[local-name()='PrivateDnsEnabled']")),
        tag_specifications: node.xpath_nodes("*[local-name()='TagSpecification']/*[local-name()='item']").map { |n| TagSpecification.from_xml(n) },
        subnet_configurations: node.xpath_nodes("*[local-name()='SubnetConfiguration']/*[local-name()='item']").map { |n| SubnetConfiguration.from_xml(n) },
        service_network_arn: Core::XMLValue.string(node.xpath_node("*[local-name()='ServiceNetworkArn']")),
        resource_configuration_arn: Core::XMLValue.string(node.xpath_node("*[local-name()='ResourceConfigurationArn']")),
        service_region: Core::XMLValue.string(node.xpath_node("*[local-name()='ServiceRegion']")),
      )
    end

    def validate! : Nil
      if value = @dns_options
        value.validate!
      end

      if value = @tag_specifications
        value.each(&.validate!)
      end

      if value = @subnet_configurations
        value.each(&.validate!)
      end
    end

    def_equals_and_hash(@dry_run, @vpc_endpoint_type, @vpc_id, @service_name, @policy_document, @route_table_ids, @subnet_ids, @security_group_ids, @ip_address_type, @dns_options, @client_token, @private_dns_enabled, @tag_specifications, @subnet_configurations, @service_network_arn, @resource_configuration_arn, @service_region)
  end
end
