#!/usr/bin/env bash

# Regenerates every service in codegen's TARGETS list and syncs the result into
# src/, replacing the modules generated by a previous run. Codegen always emits
# into tmp/ (so an incomplete run can never leave src/ half-written); this is
# the step that promotes that output into the committed tree.

set -euo pipefail

cd "$(dirname "$0")/.."

rm -rf tmp
shards run codegen

for path in tmp/*; do
  name="$(basename "$path")"
  # src/core is hand-written, and only ends up in tmp/ because compile.sh
  # copies it there to make the generated tree requireable.
  [ "$name" = "core" ] && continue
  rm -rf "src/${name}"
  cp -R "$path" "src/${name}"
done

# CI's format check covers src/, so generated code has to land formatted.
crystal tool format src
