private alias Core = Amazonite::Core

module Amazonite::EventBridgeV1
  # The details about an event generated by an SaaS partner.
  class PutPartnerEventsRequestEntry
    include JSON::Serializable

    # The date and time of the event.
    @[JSON::Field(key: "Time", converter: Core::AWSEpochConverter)]
    property time : Time | Nil

    # The event source that is generating the entry.
    #
    # `Detail`, `DetailType`, and `Source` are required for EventBridge to successfully send an event
    # to an event bus. If you include event entries in a request that do not include each of those
    # properties, EventBridge fails that entry. If you submit a request in which *none* of the entries
    # have each of these properties, EventBridge fails the entire request.
    @[JSON::Field(key: "Source")]
    property source : String | Nil

    # Amazon Web Services resources, identified by Amazon Resource Name (ARN), which the event
    # primarily concerns. Any number, including zero, may be present.
    @[JSON::Field(key: "Resources")]
    property resources : Array(String) | Nil

    # A free-form string, with a maximum of 128 characters, used to decide what fields to expect in
    # the event detail.
    #
    # `Detail`, `DetailType`, and `Source` are required for EventBridge to successfully send an event
    # to an event bus. If you include event entries in a request that do not include each of those
    # properties, EventBridge fails that entry. If you submit a request in which *none* of the entries
    # have each of these properties, EventBridge fails the entire request.
    @[JSON::Field(key: "DetailType")]
    property detail_type : String | Nil

    # A valid JSON string. There is no other schema imposed. The JSON string may contain fields and
    # nested sub-objects.
    #
    # `Detail`, `DetailType`, and `Source` are required for EventBridge to successfully send an event
    # to an event bus. If you include event entries in a request that do not include each of those
    # properties, EventBridge fails that entry. If you submit a request in which *none* of the entries
    # have each of these properties, EventBridge fails the entire request.
    @[JSON::Field(key: "Detail")]
    property detail : String | Nil

    def initialize(
      @time : Time | Nil = nil,
      @source : String | Nil = nil,
      @resources : Array(String) | Nil = nil,
      @detail_type : String | Nil = nil,
      @detail : String | Nil = nil,
    )
    end
  end
end
