private alias AI = Amazonite::IamV1
private alias Core = Amazonite::Core

module Amazonite::IamV1
  class CreateSAMLProviderRequest
    # An XML document generated by an identity provider (IdP) that supports SAML 2.0. The document
    # includes the issuer's name, expiration information, and keys that can be used to validate the
    # SAML authentication response (assertions) that are received from the IdP. You must generate the
    # metadata document using the identity management software that is used as your organization's
    # IdP.
    #
    # For more information, see [About SAML 2.0-based
    # federation](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html) in
    # the *IAM User Guide*
    property saml_metadata_document : String

    # The name of the provider to create.
    #
    # This parameter allows (through its [regex pattern](http://wikipedia.org/wiki/regex)) a string of
    # characters consisting of upper and lowercase alphanumeric characters with no spaces. You can
    # also include any of the following characters: _+=,.@-
    property name : String

    # A list of tags that you want to attach to the new IAM SAML provider. Each tag consists of a key
    # name and an associated value. For more information about tagging, see [Tagging IAM
    # resources](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html) in the *IAM User
    # Guide*.
    #
    # If any one of the tags is invalid or if you exceed the allowed maximum number of tags, then the
    # entire request fails and the resource is not created.
    property tags : Array(Tag) | Nil

    # Specifies the encryption setting for the SAML provider.
    property assertion_encryption_mode : AssertionEncryptionModeType | Nil

    # The private key generated from your external identity provider. The private key must be a .pem
    # file that uses AES-GCM or AES-CBC encryption algorithm to decrypt SAML assertions.
    property add_private_key : String | Nil

    def initialize(
      @saml_metadata_document : String,
      @name : String,
      @tags : Array(Tag) | Nil = nil,
      @assertion_encryption_mode : AssertionEncryptionModeType | Nil = nil,
      @add_private_key : String | Nil = nil,
    )
    end

    def to_query_params(prefix : String) : Array({String, String})
      params = [] of {String, String}

      params << {"#{prefix}SAMLMetadataDocument", @saml_metadata_document}

      params << {"#{prefix}Name", @name}

      (@tags || [] of Tag).each_with_index(1) do |item, i|
        params.concat(item.to_query_params("#{prefix}Tags.member.#{i}."))
      end

      if value = @assertion_encryption_mode
        params << {"#{prefix}AssertionEncryptionMode", value.to_json_object_key}
      end

      if value = @add_private_key
        params << {"#{prefix}AddPrivateKey", value}
      end
      params
    end

    def self.from_xml(node : XML::Node) : self
      new(
        saml_metadata_document: Core::XMLValue.string(node.xpath_node("*[local-name()='SAMLMetadataDocument']")).not_nil!,
        name: Core::XMLValue.string(node.xpath_node("*[local-name()='Name']")).not_nil!,
        tags: node.xpath_nodes("*[local-name()='Tags']/*[local-name()='member']").map { |n| Tag.from_xml(n) },
        assertion_encryption_mode: (n = node.xpath_node("*[local-name()='AssertionEncryptionMode']")) ? AI::AssertionEncryptionModeType.from_json_object_key?(n.content) : nil,
        add_private_key: Core::XMLValue.string(node.xpath_node("*[local-name()='AddPrivateKey']")),
      )
    end

    def validate! : Nil
      if value = @saml_metadata_document
        raise Core::ValidationError.new("SAMLMetadataDocument length must be >= 1000") if value.size < 1000
        raise Core::ValidationError.new("SAMLMetadataDocument length must be <= 10000000") if value.size > 10000000
      end

      if value = @name
        raise Core::ValidationError.new("Name length must be >= 1") if value.size < 1
        raise Core::ValidationError.new("Name length must be <= 128") if value.size > 128
        raise Core::ValidationError.new("Name does not match the required pattern") unless value.matches?(Regex.new("^[\\w._-]+$"))
      end

      if value = @tags
        raise Core::ValidationError.new("Tags must have at least 0 item(s)") if value.size < 0
        raise Core::ValidationError.new("Tags must have at most 50 item(s)") if value.size > 50
        value.each(&.validate!)
      end

      if value = @add_private_key
        raise Core::ValidationError.new("AddPrivateKey length must be >= 1") if value.size < 1
        raise Core::ValidationError.new("AddPrivateKey length must be <= 16384") if value.size > 16384
        raise Core::ValidationError.new("AddPrivateKey does not match the required pattern") unless value.matches?(Regex.new("^[\\u0009\\u000A\\u000D\\u0020-\\u00FF]+$"))
      end
    end

    def_equals_and_hash(@saml_metadata_document, @name, @tags, @assertion_encryption_mode, @add_private_key)
  end
end
