module Amazonite::ApiGateway
  # Request to add a method to an existing Resource resource.
  class PutMethodRequest
    include JSON::Serializable

    # The string identifier of the associated RestApi.
    @[JSON::Field(key: "restApiId", ignore: true)]
    property rest_api_id : String = ""

    # The Resource identifier for the new Method resource.
    @[JSON::Field(key: "resourceId", ignore: true)]
    property resource_id : String = ""

    # Specifies the method request's HTTP method type.
    @[JSON::Field(key: "httpMethod", ignore: true)]
    property http_method : String = ""

    # The method's authorization type. Valid values are `NONE` for open access, `AWS_IAM` for using
    # AWS IAM permissions, `CUSTOM` for using a custom authorizer, or `COGNITO_USER_POOLS` for using a
    # Cognito user pool.
    @[JSON::Field(key: "authorizationType")]
    property authorization_type : String

    # Specifies the identifier of an Authorizer to use on this Method, if the type is CUSTOM or
    # COGNITO_USER_POOLS. The authorizer identifier is generated by API Gateway when you created the
    # authorizer.
    @[JSON::Field(key: "authorizerId")]
    property authorizer_id : String | Nil

    # Specifies whether the method required a valid ApiKey.
    @[JSON::Field(key: "apiKeyRequired")]
    property api_key_required : Bool | Nil

    # A human-friendly operation identifier for the method. For example, you can assign the
    # `operationName` of `ListPets` for the `GET /pets` method in the `PetStore` example.
    @[JSON::Field(key: "operationName")]
    property operation_name : String | Nil

    # A key-value map defining required or optional method request parameters that can be accepted by
    # API Gateway. A key defines a method request parameter name matching the pattern of
    # `method.request.{location}.{name}`, where `location` is `querystring`, `path`, or `header` and
    # `name` is a valid and unique parameter name. The value associated with the key is a Boolean flag
    # indicating whether the parameter is required (`true`) or optional (`false`). The method request
    # parameter names defined here are available in Integration to be mapped to integration request
    # parameters or body-mapping templates.
    @[JSON::Field(key: "requestParameters")]
    property request_parameters : Hash(String, Bool) | Nil

    # Specifies the Model resources used for the request's content type. Request models are
    # represented as a key/value map, with a content type as the key and a Model name as the value.
    @[JSON::Field(key: "requestModels")]
    property request_models : Hash(String, String) | Nil

    # The identifier of a RequestValidator for validating the method request.
    @[JSON::Field(key: "requestValidatorId")]
    property request_validator_id : String | Nil

    # A list of authorization scopes configured on the method. The scopes are used with a
    # `COGNITO_USER_POOLS` authorizer to authorize the method invocation. The authorization works by
    # matching the method scopes against the scopes parsed from the access token in the incoming
    # request. The method invocation is authorized if any method scopes matches a claimed scope in the
    # access token. Otherwise, the invocation is not authorized. When the method scope is configured,
    # the client must provide an access token instead of an identity token for authorization purposes.
    @[JSON::Field(key: "authorizationScopes")]
    property authorization_scopes : Array(String) | Nil

    def initialize(
      @rest_api_id : String,
      @resource_id : String,
      @http_method : String,
      @authorization_type : String,
      @authorizer_id : String | Nil = nil,
      @api_key_required : Bool | Nil = nil,
      @operation_name : String | Nil = nil,
      @request_parameters : Hash(String, Bool) | Nil = nil,
      @request_models : Hash(String, String) | Nil = nil,
      @request_validator_id : String | Nil = nil,
      @authorization_scopes : Array(String) | Nil = nil,
    )
    end

    def validate! : Nil
    end

    def_equals_and_hash(@rest_api_id, @resource_id, @http_method, @authorization_type, @authorizer_id, @api_key_required, @operation_name, @request_parameters, @request_models, @request_validator_id, @authorization_scopes)
  end
end
