private alias AK = Amazonite::KmsV1
private alias Core = Amazonite::Core

module Amazonite::KmsV1
  class VerifyMacRequest
    include JSON::Serializable

    # The message that will be used in the verification. Enter the same message that was used to
    # generate the HMAC.
    #
    # GenerateMac and `VerifyMac` do not provide special handling for message digests. If you
    # generated an HMAC for a hash digest of a message, you must verify the HMAC for the same hash
    # digest.
    @[JSON::Field(key: "Message", converter: Core::Base64Converter)]
    property message : Bytes

    # The KMS key that will be used in the verification.
    #
    # Enter a key ID of the KMS key that was used to generate the HMAC. If you identify a different
    # KMS key, the `VerifyMac` operation fails.
    @[JSON::Field(key: "KeyId")]
    property key_id : String

    # The MAC algorithm that will be used in the verification. Enter the same MAC algorithm that was
    # used to compute the HMAC. This algorithm must be supported by the HMAC KMS key identified by the
    # `KeyId` parameter.
    @[JSON::Field(key: "MacAlgorithm", converter: AK::MacAlgorithmSpec)]
    property mac_algorithm : MacAlgorithmSpec

    # The HMAC to verify. Enter the HMAC that was generated by the GenerateMac operation when you
    # specified the same message, HMAC KMS key, and MAC algorithm as the values specified in this
    # request.
    @[JSON::Field(key: "Mac", converter: Core::Base64Converter)]
    property mac : Bytes

    # A list of grant tokens.
    #
    # Use a grant token when your permission to call this operation comes from a new grant that has
    # not yet achieved *eventual consistency*. For more information, see [Grant
    # token](https://docs.aws.amazon.com/kms/latest/developerguide/grants.html#grant_token) and [Using
    # a grant token](https://docs.aws.amazon.com/kms/latest/developerguide/using-grant-token.html) in
    # the *Key Management Service Developer Guide*.
    @[JSON::Field(key: "GrantTokens")]
    property grant_tokens : Array(String) | Nil

    # Checks if your request will succeed. `DryRun` is an optional parameter.
    #
    # To learn more about how to use this parameter, see [Testing your
    # permissions](https://docs.aws.amazon.com/kms/latest/developerguide/testing-permissions.html) in
    # the *Key Management Service Developer Guide*.
    @[JSON::Field(key: "DryRun")]
    property dry_run : Bool | Nil

    def initialize(
      @message : Bytes,
      @key_id : String,
      @mac_algorithm : MacAlgorithmSpec,
      @mac : Bytes,
      @grant_tokens : Array(String) | Nil = nil,
      @dry_run : Bool | Nil = nil,
    )
    end
  end
end
