module Amazonite::ApiGateway
  # Represents the data structure of a method's request or response payload.
  class Model
    include JSON::Serializable

    # The identifier for the model resource.
    @[JSON::Field(key: "id")]
    property id : String | Nil

    # The name of the model. Must be an alphanumeric string.
    @[JSON::Field(key: "name")]
    property name : String | Nil

    # The description of the model.
    @[JSON::Field(key: "description")]
    property description : String | Nil

    # The schema for the model. For `application/json` models, this should be JSON schema draft 4
    # model. Do not include "\*/" characters in the description of any properties because such "\*/"
    # characters may be interpreted as the closing marker for comments in some languages, such as Java
    # or JavaScript, causing the installation of your API's SDK generated by API Gateway to fail.
    @[JSON::Field(key: "schema")]
    property schema : String | Nil

    # The content-type for the model.
    @[JSON::Field(key: "contentType")]
    property content_type : String | Nil

    def initialize(
      @id : String | Nil = nil,
      @name : String | Nil = nil,
      @description : String | Nil = nil,
      @schema : String | Nil = nil,
      @content_type : String | Nil = nil,
    )
    end

    def validate! : Nil
    end

    def_equals_and_hash(@id, @name, @description, @schema, @content_type)
  end
end
